name = "wheres-my-platform"

compatibility_date = "2025-07-17"
compatibility_flags = ["nodejs_compat"]
preview_urls = true
main = "api/worker.ts"

[assets]
directory = "./html"
not_found_handling = "404-page"
binding = "ASSETS"

[observability.logs]
enabled = true
